version: 2.1

workflows:
  test:
    jobs:
      - rake_spec:
          name: test_ruby-<< matrix.ruby_version >>_bundler-<< matrix.bundler_version >>
          matrix:
            parameters:
              ruby_version:
                # - '3.2.1'
                # - '3.1.2'
                # - '3.0.5'
                - '2.7.6'
                # - '2.6.9'
                # - '2.5.9'
              bundler_version:
                - '2.4.7'
                - '2.3.26'
                - '2.2.34'
                - '2.1.4'
                - '1.17.3'

executors:
  ruby:
    parameters:
      ruby_version:
        type: string
    docker:
      - image: cimg/ruby:<< parameters.ruby_version >>

jobs:
  rake_spec:
    parameters:
      ruby_version:
        description: Ruby version
        type: string
      bundler_version:
        description: Bundler version
        type: string
    executor:
      name: ruby
      ruby_version: << parameters.ruby_version >>
    environment:
      BUNDLER_VERSION: << parameters.bundler_version >>
    steps:
      - checkout
      - run:
          name: Set Default Git Branch
          command: git config --global init.defaultBranch master
      - run:
          name: Remove Default Bundlers
          command: |-
            sudo rm -f /usr/local/lib/ruby/gems/3.2.0/specifications/default/bundler-*
            sudo rm -f /usr/local/lib/ruby/gems/3.1.0/specifications/default/bundler-*
            sudo rm -f /usr/local/lib/ruby/gems/3.0.0/specifications/default/bundler-*
            sudo rm -f /usr/local/lib/ruby/gems/2.7.0/specifications/default/bundler-*
            sudo rm -f /usr/local/lib/ruby/gems/2.6.0/specifications/default/bundler-*
            sudo rm -f /usr/local/lib/ruby/gems/2.5.0/specifications/default/bundler-*
      - run:
          name: Install Bundler
          command: gem install bundler -v << parameters.bundler_version >>
      - run:
          name: Bundle Install
          command: bundle _<< parameters.bundler_version >>_ install
      - run:
          name: Run Tests
          command: bundle _<< parameters.bundler_version >>_ exec rake spec
